# Generated by Django 3.1.10 on 2021-05-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogauthor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': 'Blog Author', 'verbose_name_plural': 'Blog Authors'},
        ),
    ]
