# Generated by Django 3.1.10 on 2021-05-14 05:43

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flex_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flex',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Your Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add Additional Text', required=True))])), ('full_richtext', streams.blocks.RichTextBlock()), ('simple_richtext', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
