# Generated by Django 3.1.10 on 2021-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email Adress', max_length=100)),
                ('full_name', models.CharField(max_length=100)),
            ],
        ),
    ]
