# Generated by Django 3.1.10 on 2021-05-17 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscribers', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
